#!/usr/bin/env python3
"""
Validate the Guardrail Engine against REAL historical default outcomes.

Every other benchmark in this repo (scripts/run_benchmark.py) evaluates
against synthetic labels generated by the same formula used to build the
training features — an internal consistency check, not proof of real-world
predictive power (see the README's Evaluation & Validation section).

This script closes that gap using Kaggle's "Give Me Some Credit" dataset
(150,000 real borrowers, real 2-year default outcomes), mirrored publicly
on OpenML with no authentication required:
https://www.openml.org/search?type=data&id=45577

Feature mapping honesty: GMSC's columns map cleanly onto SOME of
ML_FEATURE_NAMES (income, EMI-like debt ratio, active credit lines,
delinquency history) — those are REAL, derived from the dataset. The
remaining features CreditSetu computes from a full transaction history
(income stability/timing, gig pattern, rent consistency, spending
diversity, bureau score) have no equivalent in this tabular dataset and
are held at a neutral constant. This makes the resulting AUC a lower
bound / directional check on real-world discriminative power — not an
apples-to-apples comparison with the synthetic benchmark, and not a claim
that this exact number would hold on India-specific transaction data.

Usage:
    python scripts/validate_against_real_data.py
"""

import json
import subprocess
import sys
import time
from pathlib import Path
from urllib.request import urlretrieve

# Add backend root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import numpy as np
import pandas as pd

from app.engines.guardrail_engine import GuardrailEngine
from app.evaluation.metrics import ks_statistic, gini_coefficient, population_stability_index, psi_interpretation
from app.features.feature_engineering import ML_FEATURE_NAMES

DATASET_URL = "https://data.openml.org/datasets/0004/45577/dataset_45577.pq"
CACHE_PATH = Path(__file__).parent.parent / "data" / "external" / "give_me_some_credit.pq"

# Which ML_FEATURE_NAMES are derived from REAL GMSC columns vs held at a
# neutral fill value (no equivalent field in this dataset).
REAL_FEATURES = {
    "income_mean", "emi_to_inflow_ratio", "concurrent_lender_count",
    "nach_bounce_count_6m", "nach_bounce_count_3m", "monthly_surplus", "has_bureau_score",
}
NEUTRAL_FILL_FEATURES = set(ML_FEATURE_NAMES) - REAL_FEATURES


def load_dataset() -> pd.DataFrame:
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not CACHE_PATH.exists():
        print(f"Downloading Give Me Some Credit dataset from {DATASET_URL} ...")
        try:
            urlretrieve(DATASET_URL, CACHE_PATH)
        except Exception:
            # Some Python installs (notably python.org's on macOS) don't pick up
            # the system CA trust store, breaking urllib's TLS verification.
            # curl uses the OS trust store directly, so fall back to it.
            subprocess.run(["curl", "-sL", "-f", "-o", str(CACHE_PATH), DATASET_URL], check=True)
    return pd.read_parquet(CACHE_PATH)


def clean(df: pd.DataFrame) -> pd.DataFrame:
    """Filter known data-quality issues in this dataset (documented on Kaggle's forum)."""
    df = df.copy()
    df["SeriousDlqin2yrs"] = df["SeriousDlqin2yrs"].astype(int)
    df = df[(df["age"] >= 18) & (df["age"] <= 100)]
    df = df[df["DebtRatio"] < 5]  # DebtRatio >= 1 usually means MonthlyIncome was missing/garbage
    df = df.dropna(subset=["MonthlyIncome"])
    df = df[df["MonthlyIncome"] > 0]
    df = df[df["NumberOfOpenCreditLinesAndLoans"] <= 30]
    return df.reset_index(drop=True)


def remap_to_feature_schema(df: pd.DataFrame) -> pd.DataFrame:
    """Map GMSC's real columns onto CreditSetu's ML_FEATURE_NAMES."""
    debt_ratio_clipped = df["DebtRatio"].clip(0, 1)
    features = pd.DataFrame({
        "customer_id": [f"GMSC-{i}" for i in range(len(df))],
        # REAL — derived from actual GMSC columns
        "income_mean": df["MonthlyIncome"],
        "emi_to_inflow_ratio": debt_ratio_clipped,
        "concurrent_lender_count": df["NumberOfOpenCreditLinesAndLoans"],
        "nach_bounce_count_6m": (
            df["NumberOfTime30-59DaysPastDueNotWorse"]
            + df["NumberOfTime60-89DaysPastDueNotWorse"]
            + df["NumberOfTimes90DaysLate"]
        ),
        "nach_bounce_count_3m": df["NumberOfTime30-59DaysPastDueNotWorse"],
        "monthly_surplus": df["MonthlyIncome"] * (1 - debt_ratio_clipped),
        "has_bureau_score": True,  # GMSC is a bureau-scored population by construction
        # NEUTRAL FILL — no equivalent field in this tabular dataset
        "income_cv": 0.15,
        "income_timing_cv": 0.15,
        "gig_pattern_score": 0.0,
        "emi_to_inflow_trend": 0.0,
        "rent_consistency": 0.5,
        "merchant_category_entropy": 0.5,
        "bureau_score": np.nan,  # LightGBM handles this natively — same path as a real thin-file customer
    })
    return features[["customer_id"] + ML_FEATURE_NAMES]


def main():
    print("=" * 60)
    print("CreditSetu — Guardrail Engine validation against REAL default data")
    print("=" * 60)

    t0 = time.time()
    raw = clean(load_dataset())
    print(f"\nLoaded and cleaned {len(raw):,} real borrower records "
          f"({raw['SeriousDlqin2yrs'].mean():.2%} real default rate) in {time.time()-t0:.1f}s")

    features_df = remap_to_feature_schema(raw)
    customers_df = pd.DataFrame({
        "customer_id": features_df["customer_id"],
        "persona_type": "external_real_data",
        "is_stressed": raw["SeriousDlqin2yrs"].values,
    })

    print(f"\nReal features:    {sorted(REAL_FEATURES)}")
    print(f"Neutral-fill features (no equivalent in this dataset): {sorted(NEUTRAL_FILL_FEATURES)}")

    engine = GuardrailEngine()
    print("\nFitting GuardrailEngine on real historical outcomes ...")
    metrics = engine.fit(features_df, customers_df, test_size=0.2, seed=42)

    eval_data = engine.last_eval
    ks = ks_statistic(eval_data["y_test"], eval_data["y_test_pred_proba"])
    gini = gini_coefficient(metrics["auc_roc"])
    psi = population_stability_index(eval_data["train_pred_proba"], eval_data["test_pred_proba"])

    report = {
        "dataset": "Give Me Some Credit (OpenML mirror, id=45577)",
        "dataset_url": "https://www.openml.org/search?type=data&id=45577",
        "n_records": len(raw),
        "real_default_rate": round(float(raw["SeriousDlqin2yrs"].mean()), 4),
        "real_features_used": sorted(REAL_FEATURES),
        "neutral_fill_features": sorted(NEUTRAL_FILL_FEATURES),
        "auc_roc": metrics["auc_roc"],
        "ks_statistic": round(ks, 4),
        "gini_coefficient": round(gini, 4),
        "population_stability_index": round(psi, 4),
        "psi_interpretation": psi_interpretation(psi),
        "false_positive_rate": metrics["false_positive_rate"],
        "false_negative_rate": metrics["false_negative_rate"],
        "precision": metrics["precision"],
        "recall": metrics["recall"],
        "n_train": metrics["n_train"],
        "n_test": metrics["n_test"],
        "caveat": (
            f"{len(NEUTRAL_FILL_FEATURES)}/{len(ML_FEATURE_NAMES)} model features have no equivalent "
            "in this dataset and are held at a neutral constant — this AUC is a lower bound on real "
            "discriminative power, not an apples-to-apples number against the synthetic benchmark."
        ),
    }

    print("\n" + "=" * 60)
    print("RESULTS — real, non-circular validation")
    print("=" * 60)
    print(f"AUC-ROC:  {report['auc_roc']}")
    print(f"KS:       {report['ks_statistic']}")
    print(f"Gini:     {report['gini_coefficient']}")
    print(f"FPR/FNR:  {report['false_positive_rate']} / {report['false_negative_rate']}")
    print(f"\n{report['caveat']}")

    out_path = Path(__file__).parent.parent / "data" / "real_data_validation_report.json"
    with open(out_path, "w") as f:
        json.dump(report, f, indent=2)
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()
